(defstruct node tag attrs children)

(defparameter *space* '(#\Space #\Tab #\Newline #\Return))

(defun skip-space (text i)
  (loop while (and (< i (length text)) (member (char text i) *space*))
        do (incf i))
  i)

(defun parse-name (text i)
  (let ((start i))
    (loop while (and (< i (length text))
                     (not (member (char text i) (list* #\> #\/ #\= *space*))))
          do (incf i))
    (values (subseq text start i) i)))

(defun parse-attrs (text i)
  (let ((attrs '()))
    (loop
      (setf i (skip-space text i))
      (when (>= i (length text))
        (return (values (nreverse attrs) i nil)))
      (let ((c (char text i)))
        (cond
          ((char= c #\>) (return (values (nreverse attrs) (1+ i) nil)))
          ((and (char= c #\/) (< (1+ i) (length text)) (char= (char text (1+ i)) #\>))
           (return (values (nreverse attrs) (+ i 2) t)))
          (t
           (multiple-value-bind (name j) (parse-name text i)
             (setf i (skip-space text j))
             (if (and (< i (length text)) (char= (char text i) #\=))
                 (progn
                   (setf i (skip-space text (1+ i)))
                   (let ((quote-char (char text i))
                         (start (1+ i)))
                     (setf i (1+ i))
                     (loop while (and (< i (length text)) (char/= (char text i) quote-char))
                           do (incf i))
                     (push (cons name (subseq text start i)) attrs)
                     (incf i)))
                 (push (cons name "") attrs)))))))))

(defun parse-node (text i)
  (multiple-value-bind (tag j) (parse-name text (1+ i))
    (multiple-value-bind (attrs k self-closing) (parse-attrs text j)
      (if self-closing
          (values (make-node :tag tag :attrs attrs :children nil) k)
          (multiple-value-bind (children m) (parse-children text k)
            (values (make-node :tag tag :attrs attrs :children children) m))))))

(defun parse-children (text i)
  (let ((children '()))
    (loop
      (when (>= i (length text))
        (return (values (nreverse children) i)))
      (if (char= (char text i) #\<)
          (cond
            ((and (< (1+ i) (length text)) (char= (char text (1+ i)) #\/))
             (return (values (nreverse children) (1+ (position #\> text :start i)))))
            ((and (< (+ i 4) (length text)) (string= "<!--" (subseq text i (+ i 4))))
             (setf i (+ 3 (search "-->" text :start2 i))))
            ((char= (char text (1+ i)) #\?)
             (setf i (+ 2 (search "?>" text :start2 i))))
            (t
             (multiple-value-bind (child j) (parse-node text i)
               (push child children)
               (setf i j))))
          (let* ((next (or (position #\< text :start i) (length text)))
                 (chunk (string-trim *space* (subseq text i next))))
            (when (plusp (length chunk))
              (push chunk children))
            (setf i next))))))

(defun parse-xml (text)
  (let ((i (skip-space text 0)))
    (loop while (and (< (1+ i) (length text))
                     (char= (char text i) #\<)
                     (member (char text (1+ i)) '(#\? #\!)))
          do (let ((end (position #\> text :start i)))
               (setf i (skip-space text (1+ end)))))
    (parse-node text i)))

(defun text-of (element)
  (with-output-to-string (out)
    (dolist (child (node-children element))
      (when (stringp child)
        (write-string child out)))))

(defun collect (element tag result)
  (when (string= (node-tag element) tag)
    (push element (cdr result)))
  (dolist (child (node-children element))
    (unless (stringp child)
      (collect child tag result)))
  result)

(defun fields-of (record)
  (let ((fields '()))
    (dolist (attr (node-attrs record))
      (push (cons (concatenate 'string "@" (car attr)) (cdr attr)) fields))
    (dolist (child (node-children record))
      (unless (stringp child)
        (push (cons (node-tag child) (text-of child)) fields)))
    (nreverse fields)))

(defun csv-cell (value)
  (if (or (find #\, value) (find #\" value) (find #\Newline value))
      (with-output-to-string (out)
        (write-char #\" out)
        (loop for c across value
              do (progn (when (char= c #\") (write-char #\" out))
                        (write-char c out)))
        (write-char #\" out))
      value))

(defun main ()
  (let ((args (rest sb-ext:*posix-argv*)))
    (when (< (length args) 3)
      (format t "Использование: sbcl --script xml2csv.lisp <вход.xml> <выход.csv> <тег записи>~%")
      (sb-ext:exit :code 1))

    (let* ((source (first args))
           (target (second args))
           (record-tag (third args))
           (text (with-open-file (in source :external-format :utf-8)
                   (let ((buffer (make-string (file-length in))))
                     (subseq buffer 0 (read-sequence buffer in)))))
           (tree (parse-xml text))
           (records (reverse (cdr (collect tree record-tag (cons :records nil))))))

      (when (null records)
        (format t "В документе нет записей с тегом <~a>~%" record-tag)
        (sb-ext:exit :code 1))

      (let ((columns '()))
        (dolist (record records)
          (dolist (field (fields-of record))
            (pushnew (car field) columns :test #'string=)))
        (setf columns (nreverse columns))

        (with-open-file (out target :direction :output :if-exists :supersede
                                    :external-format :utf-8)
          (format out "~{~a~^,~}~%" (mapcar #'csv-cell columns))
          (dolist (record records)
            (let ((fields (fields-of record)))
              (format out "~{~a~^,~}~%"
                      (mapcar (lambda (column)
                                (csv-cell (or (cdr (assoc column fields :test #'string=)) "")))
                              columns)))))

        (format t "Записей: ~a~%" (length records))
        (format t "Полей:   ~a (~{~a~^, ~})~%" (length columns) columns)
        (format t "Записано в ~a~%" target)))))

(main)
